=== AlexOllero/AlexOllero.github.io/xml/recetas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="recetas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Receta">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Ingredientes" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Ingrediente"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Receta2">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Ingredientes" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Ingrediente2"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AlexOllero/AlexOllero.github.io/xml/recetas.xml
<?xml version="1.0" encoding="UTF-8"?>
<recetas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="recetas.xsd">
      <Receta>
          <Ingredientes>
              <Ingrediente>Patatas</Ingrediente>
            </Ingredientes>
            
            <Ingredientes>
              <Ingrediente>Huevos</Ingrediente>
            </Ingredientes>
              
              <Ingredientes>
              <Ingrediente>Aceite de oliva</Ingrediente>
              </Ingredientes>
              <Ingredientes>
              <Ingrediente>Cebolla</Ingrediente>
              </Ingredientes>
              <Ingredientes>
              <Ingrediente>Sal</Ingrediente>
              </Ingredientes>
         
      </Receta>
      
      <Receta2>
        <Ingredientes>
              <Ingrediente2>Arroz</Ingrediente2>
              </Ingredientes>
              <Ingredientes>
              <Ingrediente2>Tomate frito</Ingrediente2>
              </Ingredientes>
              <Ingredientes>
              <Ingrediente2>Platano</Ingrediente2>
              </Ingredientes>
              <Ingredientes>
              <Ingrediente2>Huevos</Ingrediente2>
              </Ingredientes>
              <Ingredientes>
              <Ingrediente2>Sal</Ingrediente2>
              </Ingredientes>
              <Ingredientes>
              <Ingrediente2>Ajo</Ingrediente2>
              </Ingredientes>
              <Ingredientes>
              <Ingrediente2>Laurel</Ingrediente2>
        </Ingredientes>
      
      </Receta2>

</recetas>
